### ISSUE TITLE
not compatible anymore

### ISSUE THREAD

**Issue by Grummfy** [pavlakis/slim-behat-extension#3]
Hello,
with last version of slipm & behat it's not working properly anymore (change in one of the symfony components).
For information, now I use this https://github.com/ciaranmcnulty/behat-psr7extension that is less advanced but working properly.

**Comment by pavlakis** [comment]
@Grummfy can you provide more information on what exactly is wrong with it?
I am currently using it in a project and still works fine for me. Just in case, I did update the documentation to make the setup a bit clearer.

**Comment by Grummfy** [comment]
i got a dependency issue related to incompatibility in one of the module. I should have posted the error at this time ;( Sorry to forget it.

I will see if I got time to deal with it.

**Comment by pavlakis** [comment]
Documentation has been updated with more examples on how to use it. If you're still having problems, please open a new issue.
